@DreamBig.Portfolios.Web.Api_HostAddress = http://localhost:7288

GET {{DreamBig.Portfolios.Web.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{DreamBig.Portfolios.Web.Api_HostAddress}}/_health
Accept: application/json

###

GET {{DreamBig.Portfolios.Web.Api_HostAddress}}/profile
Accept: application/json

###

GET {{DreamBig.Portfolios.Web.Api_HostAddress}}/posts/146e21c1-b18e-429b-8bfd-72f5e183f989
Accept: application/json

###